name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-retag.yaml@dns-friendly-versions-and-strip-prefi
    permissions:
      contents: write
      packages: write
      checks: write
